name: Build Windows Container

on:
  push:
    branches: [main]
    paths: ['Dockerfile.windows', 'backend/**']
  pull_request:
    branches: [main]
    paths: ['Dockerfile.windows', 'backend/**']
  workflow_dispatch:

jobs:
  build-windows-container:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Windows Container
      run: |
        docker build -f Dockerfile.windows -t crystal-copilot-windows:latest .
        
    - name: Test Container
      run: |
        docker run --rm crystal-copilot-windows:latest python test_container.py
        
    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push to GitHub Container Registry
      if: github.event_name != 'pull_request'
      run: |
        docker tag crystal-copilot-windows:latest ghcr.io/${{ github.repository_owner }}/crystal-copilot-windows:latest
        docker push ghcr.io/${{ github.repository_owner }}/crystal-copilot-windows:latest
